### ISSUE TITLE
Last chance to update resquework.org's DNS settings

### ISSUE THREAD

**Issue by mcfiredrill** [resque/resque.github.com#9]
Got this email about a week ago:

```
Hi there resque,

We wanted to follow-up on the email we sent back you in November about custom domains on GitHub Pages sites. To help us improve how we serve GitHub Pages, we’re deprecating our old GitHub Pages IP addresses.

The following domains owned by your account will be affected by this deprecation:

resquework.org (hosted at https://github.com/resque/resque.github.com)
Because your custom domain is pointed at a legacy IP, you’ll need to update your DNS configuration before February 2, 2015 to keep things running smoothly.

```

Looks like we have until Feb 2nd. Anyone know who owns the resquework.org domain?

**Comment by mcfiredrill** [comment]
Got another email about it "final notice", anyone own resquework.org? @steveklabnik @yaauie @tarcieri anyone know?

**Comment by steveklabnik** [comment]
Yes, I own it, and I got the email too. I'm in the middle of a two-week
international trip, so I'll take care of it, though it might take me a few
days.

**Comment by mcfiredrill** [comment]
@steveklabnik Thanks Steve! Have a good trip. :airplane: :airplane:

**Comment by harry-wood** [comment]
resquework.org is a spamdexing domain squatter now, so I guess you can close this.
